### ISSUE TITLE
3.5 vs 3.6

### ISSUE THREAD

**Issue by arendej** [RedHatWorkshops/openshiftv3-ops-workshop#3]
For 
https://github.com/RedHatWorkshops/openshiftv3-ops-workshop/blob/master/cns.md
I've just done this CNS deployment method in an OCP 3.6 cluster... update doc accordingly? or wait for more 3.6 feedback?

**Comment by christianh814** [comment]
I've done these steps on 3.6 and the steps are exactly the same.

I would like to update this, however, to reflect `cns-deploy` of the block provisioner and object storage parts. Which requires more testing.

Have you tested the block and object storage parts?

**Comment by christianh814** [comment]
Closing. This has been addressed in commit  f76419fd8304554f1be3b194623a3d7a28c7987f
